[Database]
host="127.0.0.1"
port=3306
database="minecraft"
username="minecraft"
password="minecraft"

[Messages]
kick-format="You were kicked.<newline>Reason: %reason%"
ban-format="You were permanently banned.<newline>Reason: %reason%"
tempban-format="You were banned until %time%.<newline>Reason: %reason%"
no-reason="No reason provided."
